version: "3.8"

services:
  web:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
    command: go run main.go
  db:
    build: 
      context: .
      dockerfile: ./Dockerfile.db 
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/migrations
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
